### ISSUE TITLE
Missing "tokens/kerberos" in API

### ISSUE THREAD

**Issue by pcabreracamara** [LuatixHQ/openex#1]
Hi all,

I have just successfully installed openex frontend, worker and api. Once the frontend is published in port 3000, when I try to logging, I see a POST request to "path/api/tokens"

(path is the variable "openex.api" configured in openex-worker/distribution/target/assembly/openex/openex.properties)

POST /openex-api/web/api/tokens HTTP/1.1
x-forwarded-host: localhost:3000
x-forwarded-proto: http
x-forwarded-port: 3000
x-forwarded-for: 127.0.0.1
connection: close
dnt: 1
content-length: 108
referer: http://localhost:3000/
responsetype: json
x-authorization-token: undefined
content-type: application/json;charset=utf-8
accept-encoding: gzip, deflate
accept-language: en-US,en;q=0.5
accept: application/json, text/plain, */*
user-agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:54.0) Gecko/20100101 Firefox/54.0
host: localhost

{"login":"jane@openex.io","password":"KDoMBaeAKu0xMZgLGsAWjsJFBf/o/sv0xlPoVA6arzHXyUrBeXL4zkuOLEFrqxuob/0="}

The path api/tokens does not exist. Please could help me to configure the openex-api so I can loggin ?

Regards,
Pedro

**Comment by SamuelHassine** [comment]
Hello,

When you start the frontend in developer mode (_yarn start_), you have to set the "proxy" (_"proxy": "http://dev.local.openex.io/"_) in the package.json with the URL of the API deployment.

Let me know if it solves your problem.

Best regards,
Samuel

**Comment by pcabreracamara** [comment]
Hello,

I set the proxy variable to point the "openex-api/web" path. Is this correct ? As far as I understand this variable should point to openex-api web pages, if I'm not mistaken.

Best regards,
Pedro

**Comment by SamuelHassine** [comment]
Hellon

No, the proxy variable must point to the full URL of the API, which have to be lauched on a webserver. This variable is used only if you start the frontend through the command "yarn start". In the package that you are able to download on the website, frontend and API are merged in one Symfony application.

Best regards,
Samuel

**Comment by pcabreracamara** [comment]
Hello,

The proxy variable is pointing the full URL in the _package.json_:

` "proxy": "http://localhost/openex-api/web/",`

and yes, I'm starting the openex-frontend through the command "yarn start". The openex-api is configured with apache webserver, and is browseable:

![screen](https://user-images.githubusercontent.com/8314063/37373005-1eb37b64-2715-11e8-9324-7673c333d568.png)

The openex-api was installed following the github instructions, and the database was successfully initialised. 

Regards,
Pedro
